include: package:pedantic/analysis_options.yaml
linter:
  rules:
    - prefer_equal_for_default_values
    - prefer_generic_function_type_aliases
    - slash_for_doc_comments
    - unawaited_futures
    - unnecessary_const
    - unnecessary_new
